//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PW_Final
{
    using System;
    using System.Collections.Generic;
    
    public partial class Oficina
    {
        public int Id { get; set; }
        public string Nome { get; set; }
        public string Morada { get; set; }
        public string Telefone { get; set; }
        public int TipoReparacaoId { get; set; }
        public string Avaliacao { get; set; }
    
        public virtual TipoReparacao TipoReparacao { get; set; }
        public virtual RespostaPedido RespostaPedido { get; set; }
    }
}
