//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PW_Final
{
    using System;
    using System.Collections.Generic;
    
    public partial class PedidoReparacao
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PedidoReparacao()
        {
            this.RespostaPedido = new HashSet<RespostaPedido>();
        }
    
        public int Id { get; set; }
        public string DescricaoAvaria { get; set; }
        public System.DateTime DataPedido { get; set; }
        public short Avaliacao { get; set; }
        public string AspNetUsersId { get; set; }
        public int TipoReparacaoId { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual TipoReparacao TipoReparacao { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RespostaPedido> RespostaPedido { get; set; }
    }
}
